# Generated by Django 4.2.30 on 2026-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'ip_address'], name='core_logina_usernam_a2eb75_idx')],
            },
        ),
    ]
