# Generated by Django 4.2.30 on 2026-09-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('sales_trend', 'Sales Trend'), ('customer_segmentation', 'Customer Segmentation'), ('demand_forecast', 'Demand Forecast')], max_length=30)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
