# Generated by Django 4.2.30 on 2026-10-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_summary', 'Sales Summary'), ('demand_forecast', 'Demand Forecast Matrix'), ('anomaly_alerts', 'Anomaly Alerts'), ('customer_segments', 'Customer Segments (RFM)'), ('accounts_receivable', 'Accounts Receivable Summary'), ('sales_trend', 'Sales Trend'), ('customer_segmentation', 'Customer Segmentation')], max_length=30),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_confidence', models.FloatField(default=0.85, help_text='Statistical confidence threshold for forecasting (0.50 - 0.99).')),
                ('forecast_horizon_days', models.PositiveIntegerField(default=30, help_text='Demand forecast horizon in days (7 - 90).')),
                ('forecast_cache_timeout', models.PositiveIntegerField(default=60, help_text='Forecasting computation cache timeout in minutes (5 - 1440).')),
                ('anomaly_contamination', models.FloatField(default=0.05, help_text='Expected proportion of anomalies in order stream (0.01 - 0.20).')),
                ('customer_segment_clusters', models.PositiveIntegerField(default=3, help_text='Number of behavioral RFM clusters (2 - 6).')),
                ('email_alerts_anomaly', models.BooleanField(default=True, help_text='Send immediate email alerts to Operations Manager on high-priority ML anomalies.')),
                ('stock_alerts_warehouse', models.BooleanField(default=True, help_text='Notify Warehouse Officer immediately on critical low stock components.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
