# Generated by Django 4.2.30 on 2026-10-08 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_alter_report_report_type_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('forecasting', 'Demand Forecasting (SARIMAX)'), ('anomaly', 'Anomaly Detection (Isolation Forest)'), ('segmentation', 'Customer Segmentation (K-Means)')], max_length=30)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model Run',
                'verbose_name_plural': 'ML Model Runs',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnomalyRecord',
            fields=[
                ('anomaly_id', models.AutoField(primary_key=True, serialize=False)),
                ('anomaly_score', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Anomaly'), ('false_positive', 'False Positive (Dismissed)')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_records', to='analytics.mlmodelrun')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_records', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Anomaly Record',
                'verbose_name_plural': 'Order Anomaly Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecastRecord',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_quantity', models.FloatField()),
                ('confidence_lower', models.FloatField(default=0.0)),
                ('confidence_upper', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_records', to='analytics.mlmodelrun')),
            ],
            options={
                'verbose_name': 'Demand Forecast Record',
                'verbose_name_plural': 'Demand Forecast Records',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegmentRecord',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('recency_days', models.IntegerField()),
                ('order_frequency', models.IntegerField()),
                ('monetary_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cluster_id', models.IntegerField()),
                ('cluster_label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_records', to='orders.customer')),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_records', to='analytics.mlmodelrun')),
            ],
            options={
                'verbose_name': 'Customer Segment Record',
                'verbose_name_plural': 'Customer Segment Records',
                'ordering': ['cluster_id', '-monetary_spend'],
            },
        ),
    ]
