# Generated by Django 4.2.30 on 2026-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_notes',
            field=models.TextField(blank=True, default='', help_text='Dispatch vehicle, driver, or warehouse notes'),
        ),
    ]
